version: '3.8'

services:
  supabase-test:
    image: node:20-alpine
    container_name: supabase-test
    working_dir: /app
    volumes:
      - ./test-supabase.js:/app/test-supabase.js
      - ./server.js:/app/server.js
      - ./package.json:/app/package.json
    ports:
      - "3000:3000"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - TEST_EMAIL=${TEST_EMAIL}
      - TEST_PASSWORD=${TEST_PASSWORD}
      - AUTO_EMAIL=${AUTO_EMAIL}
      - PORT=3000
    command: sh -c "npm install && node server.js"
    restart: unless-stopped
    networks:
      - supabase-network

networks:
  supabase-network:
    driver: bridge
